### ISSUE TITLE
v1 Refactor

### ISSUE THREAD

**Issue by chrisui** [chrisui/react-hotkeys#24]
Issue to track/discuss upcoming features/changes.
- [ ] Allow controlling parent/child mapping (in case it doesn't quite correlate with dom output - eg. imagine a contextual menu being mounted through a portal)
- [ ] Higher order component api
- [ ] Allow bubbling of event/hotkeys https://github.com/chrisui/react-hotkeys/issues/52
  - [ ] Explore "hotkey event" api as discussed in https://github.com/Chrisui/react-hotkeys/issues/20
- [x] Tests
- [ ] Explore possible single mousetrap/dom binding - https://github.com/chrisui/react-hotkeys/issues/2
- [ ] Expose `Mousetrap` reference (ie. `import {Mousetrap} from 'react-hotkeys';`) 
- [ ] Investigate binding (inputs?) issues https://github.com/chrisui/react-hotkeys/issues/51

**Comment by Chrisui** [comment]
Potentially provide first class support for initial focus state?

See: https://github.com/Chrisui/react-hotkeys/issues/25

**Comment by MLoughry** [comment]
@chrisui In my project, I'm already working on an HOC API wrapper around this project that I may be able to port over to this project. However, without PR #40 (or at least allowing the wrapping div to be styled), it has some issues.

The working prototype I have provides

- @registerKeyMap class decorator that takes in a keyMap argument, and wraps the class's render method in a <HotKeys keyMap={arg}> component
- @keydownHandler method decorator that takes in a string command argument. It then wraps the class's render method with a <HotKeys handler={handlers}> method with a map of all decorated methods in the class.

However, I want to be sure this project is still open to development before spending effort porting my prototype to this project.

**Comment by chrisui** [comment]
Have _*finally*_ (!!?!?!) kicked off this work. First priority has been getting everything updated (a lot has changed in 2 years!) and ensuring we have a robust way of testing the hotkey events so we can have good coverage. Still working on that latter part but hopefully have something to show soon!

**Comment by greena13** [comment]
Closing to track the issues individually - milestones are now being used to group issues.
